version: '3.0'
services:
  MixerDB:
    container_name: MixerDB
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_USER=mixeruser
      - POSTGRES_PASSWORD=mixerpassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
  MixerBackend:
    container_name: MixerBackend
    image: mixeway/backend:latest
    env_file:
      - environments
    ports:
      - 8443:8443
    volumes:
      - ./pki/:/etc/pki
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - MixerDB
  MixerFrontend:
    container_name: MixerFrontend
    image: mixeway/frontend:latest
    volumes:
      - ./pki/:/etc/pki
    ports:
      - 443:443
    depends_on:
      - MixerBackend
  MixewayVulnAuditor:
    container_name: MixewayVulnAuditor
    image: mixeway/vulnauditor:latest
    env_file:
      - environments
    volumes:
      - ./pki/:/pki/
    ports:
      - 8445:8445
volumes:
  pgdata:

