version: '3.0'
services:
  MixerDB:
    container_name: MixerDB
    image: postgres:14
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: mixer
      POSTGRES_USER: mixeruser
      POSTGRES_PASSWORD: mixerpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
volumes:
  pgdata:

